name: CI

on: [push, pull_request, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build Anura
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - run: sudo apt update
            - run: sudo apt install -y git build-essential clang default-jre
            - run: git submodule update --init
            - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            - run: source "$HOME/.cargo/env" && make static
            - run: zip -r anura.zip static/
            - uses: actions/upload-artifact@v4
              with:
                  name: Anura static build
                  path: anura.zip
                  retention-days: 2

    upload:
        name: Upload release
        runs-on: ubuntu-latest
        needs: build
        permissions: write-all
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Delete old release and tag
              uses: dev-drprasad/delete-tag-and-release@v1.0.1
              with:
                  delete_release: true
                  tag_name: latest
                  github_token: ${{ github.token }}

            - name: Get artifacts
              uses: actions/download-artifact@v4
              with:
                  name: Anura Static Build
                  path: .

            - name: Release to GitHub
              uses: ncipollo/release-action@v1
              with:
                  name: Continuous Build
                  tag: latest
                  commit: main
                  body: "${{ github.event.head_commit.url }} ${{ github.event.head_commit.message }}"
                  artifacts: "anura.zip"
                  prerelease: true
